In [24]:
! pip install pandas
! pip install openpyxl

Requirement already satisfied: pandas in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: openpyxl in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from openpyxl) (2.0.0)

In [25]:
import pandas as pd
import json

In [26]:
xl_path = '../data/xl/dados_metas_atualizados_v2.xlsx'

In [27]:
df = pd.read_excel(xl_path, engine='openpyxl', sheet_name='acoes_estrategicas')

In [28]:
df.head()

,Número da Meta,Descrição da Meta,Número da Ação Estratégica,Descrição da Ação Estratégica,Secretaria
0,2,"Requalificar ou ampliar 25 parques, com a melh...",2.01,Requalificação do Parque Jardim da Luz.,SVMA
1,2,"Requalificar ou ampliar 25 parques, com a melh...",2.02,Requalificação do Parque do Carmo.,SVMA
2,2,"Requalificar ou ampliar 25 parques, com a melh...",2.03,Requalificação da Marquise do Parque Ibirapuera.,SVMA
3,2,"Requalificar ou ampliar 25 parques, com a melh...",2.04,Disponibilização de Guia Metodológico para ela...,SVMA
4,2,"Requalificar ou ampliar 25 parques, com a melh...",2.05,Entrega de pelo menos 10 planos de gestão dent...,SVMA

In [29]:
renomear = {
    'Número da Meta': 'numero_meta',
    'Número da Ação Estratégica' : 'numero_acao' ,
    'Descrição da Ação Estratégica' : 'desc_acao',
    'Secretaria' : 'orgao_acao'
}

In [30]:
df.rename(columns=renomear, inplace=True)

In [31]:
df = df[renomear.values()].copy()

In [32]:
df.head()

,numero_meta,numero_acao,desc_acao,orgao_acao
0,2,2.01,Requalificação do Parque Jardim da Luz.,SVMA
1,2,2.02,Requalificação do Parque do Carmo.,SVMA
2,2,2.03,Requalificação da Marquise do Parque Ibirapuera.,SVMA
3,2,2.04,Disponibilização de Guia Metodológico para ela...,SVMA
4,2,2.05,Entrega de pelo menos 10 planos de gestão dent...,SVMA

In [33]:
renomear_orgaos = {
    'SP REGULA' : 'SPRegula',
    'SPTRANS' : 'SPTrans',
    'SP TRANS' : 'SPTrans',
    'SP OBRAS' : 'SPObras',
    'SGM/SEDP' : 'SEDP',
    'SP URBANISMO' : 'SPUrbanismo',
    'SGM/SEPE' : 'SEPE',
    'SMDHC/SESANA' : 'SESANA',
    'SUBPREFEITURAS' : 'SMSUB'

}

for atual, novo in renomear_orgaos.items():

    df['orgao_acao'] = df['orgao_acao'].str.replace(atual, novo)

In [34]:
acoes_parsed = []

for i, row in df.iterrows():

    orgaos = [secretaria.strip() for secretaria in row['orgao_acao'].split(';')
              if secretaria.strip()]

    acao = {
        'numero_meta': row['numero_meta'],
        'numero_acao': row['numero_acao'],
        'desc_acao': row['desc_acao'],
        'orgao_acao': orgaos
    }
    acoes_parsed.append(acao)

In [35]:
with open('../data/acoes_estrategicas.json', 'w', encoding='utf-8') as f:
    json.dump(acoes_parsed, f, indent=4, ensure_ascii=False)