In [1]:
! pip install pandas
! pip install openpyxl

Requirement already satisfied: pandas in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: openpyxl in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from openpyxl) (2.0.0)

In [2]:
import pandas as pd
import json

In [3]:
xl_path = '../data/xl/dados_metas_atualizados.xlsx'

In [4]:
df = pd.read_excel(xl_path, engine='openpyxl', sheet_name='Temas, Planos e ODS')

In [5]:
df.head()

,Número da Meta,Destaque do Título,Descrição da Meta,Projeção,Indicador,Unnamed: 5,Secretaria,Eixo,Temas,Subprefeituras,ODS,Nº da Meta ODS,Planos Municipais
0,1,Entregar 8 novos parques,"Entregar 8 novos parques, para ampliar a ofert...","Com essa medida, a cidade chegará a 125 parque...",Número de parques entregues.,NaN,SVMA,Universo SP,Natureza e ambiente,Campo Limpo; Casa Verde/Cachoeirinha; Cidade A...,11; 13; 15,11.7; 15.1; 13.1,Plano Diretor Estratégico; Plano Municipal de ...
1,2,Requalificar ou ampliar 25 parques,"Requalificar ou ampliar 25 parques, com a melh...",Serão priorizadas as unidades com indicadores ...,Número de parques revitalizados.,NaN,SVMA,Universo SP,Natureza e ambiente,Butantã; Capão Redondo; Ermelino Matarazzo; It...,11; 13; 15,11.7; 15.1; 13.1,Plano Diretor Estratégico; Plano Municipal de ...
2,3,Realizar o projeto São Paulo +Verde,"Realizar o projeto São Paulo +Verde, que vai p...",A iniciativa envolve o plantio de árvores em p...,Número de árvores plantadas.,NaN,SVMA; SMSUB,Universo SP,Natureza e ambiente,NaN,2; 11; 13; 15,2.5; 11.7; 13.1; 15.1; 15.2,Plano Municipal de Arborização Urbana
3,4,"Alcançar 11,4% de tratamento de materiais reci...","Alcançar 11,4% de tratamento de materiais reci...",O aumento da capacidade de separação de resídu...,Percentual de resíduos recicláveis não destina...,NaN,SP REGULA; SMSUB; SMDET,Universo SP,Natureza e ambiente,NaN,12; 16,12.5; 16.6,Plano de Gestão Integrada de Resíduos Sólidos
4,5,Levar atividades de conscientização e educação...,Levar atividades de conscientização e educação...,Além de cursos e atividades formativas da Univ...,Número de atendimentos em ações de educação am...,NaN,SVMA,Universo SP,Natureza e ambiente,NaN,3; 9; 16,3.6; 9.1; 16.6,Plano Municipal de Educação Ambiental

In [6]:
renomear = {
    'Número da Meta' : 'meta_numero',
    'Temas' : 'tema',
    'Eixo' : 'eixo'
}

In [7]:
df.rename(columns=renomear, inplace=True)

In [8]:
df = df[renomear.values()].copy()

In [9]:
df.head()

   meta_numero                 tema         eixo
0            1  Natureza e ambiente  Universo SP
1            2  Natureza e ambiente  Universo SP
2            3  Natureza e ambiente  Universo SP
3            4  Natureza e ambiente  Universo SP
4            5  Natureza e ambiente  Universo SP

In [10]:
df['tema'].str.split(';').apply(lambda x: len(x)).max()

np.int64(1)

In [11]:
df['tema'].unique()

array(['Natureza e ambiente', 'Habitação de qualidade',
       'Infraestrutura e integração', 'Mobilidade',
       'Requalificação urbana', 'Segurança', 'Saúde e bem-estar',
       'Educação', 'Proteção social e cidadania plena',
       'Cultura, Esporte e Lazer', 'Ambiente de negócios',
       'Economia criativa', 'Qualificação profissional, emprego e renda',
       'Modernização e inovação', 'Transparência e participação cidadã',
       'Governo ágil e acessível a todos'], dtype=object)

In [12]:
path_dados_eixos = '../data/eixos.json'

with open(path_dados_eixos, 'r') as f:
    dados_eixos = json.load(f)

In [13]:
dados_eixos[1]

{'nome': 'Viver São Paulo',
 'titulo': 'pessoas e sociedade',
 'descricao': 'O eixo Viver São Paulo concentra as metas mais diretamente associadas à qualidade de vida do cidadão. É onde se situam as ações que proporcionam condições para viver plenamente a cidade, com dignidade, bem-estar e pertencimento.\nÉ o eixo da segurança pública, da proteção à mulher vítima de violência, da segurança alimentar e nutricional, do acolhimento à população em situação de rua, dos serviços de saúde, da educação e da cultura como dimensões indissociáveis da formação humana, do esporte, do lazer, da convivência respeitosa e pacífica.\nViver São Paulo é, em última instância, viver com direitos, serviços e oportunidades. É viver as relações com outras pessoas. É ser parte, ter lugar e ter voz na sociedade.',
 'resumo': 'Este eixo concentra as metas mais diretamente associadas à qualidade de vida do cidadão. É onde se situam as ações que proporcionam condições para viver plenamente a cidade, com dignidade, bem-estar e pertencimento.',
 'logo_colorido_path': 'viver_sp_colorido.svg',
 'logo_branco_path': 'viver_sao_paulo_branco.svg',
 'hex_cor_principal': '#EF4C23',
 'ordem': 1,
 'orcamento': 16500000000,
 'temas': [{'nome': 'Segurança', 'descricao': 'XXXX'},
  {'nome': 'Saúde e bem-estar', 'descricao': 'XXXX'},
  {'nome': 'Educação', 'descricao': 'XXXX'},
  {'nome': 'Proteção social e cidadania plena', 'descricao': 'XXXX'},
  {'nome': 'Cultura, Esporte e Lazer', 'descricao': 'XXXX'}]}

In [14]:
temas_unicos = set()
for eixo in dados_eixos:
    for tema in eixo['temas']:
        temas_unicos.add(tema['nome'])

In [15]:
temas_unicos

{'Ambiente de negócios',
 'Cultura, Esporte e Lazer',
 'Economia criativa',
 'Educação',
 'Governo ágil e acessível a todos',
 'Habitação de qualidade',
 'Infraestrutura e integração',
 'Mobilidade',
 'Modernização e inovação',
 'Natureza e ambiente',
 'Proteção social e cidadania plena',
 'Qualificação profissional, emprego e renda',
 'Requalificação urbana',
 'Saúde e bem-estar',
 'Segurança',
 'Transparência e participação cidadã'}

In [16]:
temas_unicos - set(df['tema'].unique())

set()

In [17]:
set(df['tema'].unique()) - temas_unicos

set()

## Existem temas novos

Como, para além das diferenças de grafias, parecem ter surgido temas novos, vou atualizar os temas em si.

In [18]:
df_eixos = df[['eixo', 'tema']].drop_duplicates().reset_index(drop=True)

In [19]:
df_eixos.head()

          eixo                         tema
0  Universo SP          Natureza e ambiente
1  Universo SP       Habitação de qualidade
2  Universo SP  Infraestrutura e integração
3  Universo SP                   Mobilidade
4  Universo SP        Requalificação urbana

In [20]:
def get_dados_eixo(nome_eixo):
    for eixo in dados_eixos:
        if eixo['nome'] == nome_eixo:
            return eixo
    raise ValueError(f'Eixo {nome_eixo} não encontrado')

In [21]:
dados_temas_eixos = {}
new_dados_eixos = []

eixos = df_eixos['eixo'].unique()
for eixo in eixos:
    
    dados_eixo = get_dados_eixo(eixo)
    dados_eixo['temas'] = []
    temas_eixo = df_eixos[df_eixos['eixo']==eixo]['tema']

    for tema in temas_eixo:
        dados_eixo['temas'].append({
            'nome' : tema,
            'descricao' : 'XXXX'
        })

    new_dados_eixos.append(dados_eixo)

In [22]:
new_dados_eixos[1]

{'nome': 'Viver São Paulo',
 'titulo': 'pessoas e sociedade',
 'descricao': 'O eixo Viver São Paulo concentra as metas mais diretamente associadas à qualidade de vida do cidadão. É onde se situam as ações que proporcionam condições para viver plenamente a cidade, com dignidade, bem-estar e pertencimento.\nÉ o eixo da segurança pública, da proteção à mulher vítima de violência, da segurança alimentar e nutricional, do acolhimento à população em situação de rua, dos serviços de saúde, da educação e da cultura como dimensões indissociáveis da formação humana, do esporte, do lazer, da convivência respeitosa e pacífica.\nViver São Paulo é, em última instância, viver com direitos, serviços e oportunidades. É viver as relações com outras pessoas. É ser parte, ter lugar e ter voz na sociedade.',
 'resumo': 'Este eixo concentra as metas mais diretamente associadas à qualidade de vida do cidadão. É onde se situam as ações que proporcionam condições para viver plenamente a cidade, com dignidade, bem-estar e pertencimento.',
 'logo_colorido_path': 'viver_sp_colorido.svg',
 'logo_branco_path': 'viver_sao_paulo_branco.svg',
 'hex_cor_principal': '#EF4C23',
 'ordem': 1,
 'orcamento': 16500000000,
 'temas': [{'nome': 'Segurança', 'descricao': 'XXXX'},
  {'nome': 'Saúde e bem-estar', 'descricao': 'XXXX'},
  {'nome': 'Educação', 'descricao': 'XXXX'},
  {'nome': 'Proteção social e cidadania plena', 'descricao': 'XXXX'},
  {'nome': 'Cultura, Esporte e Lazer', 'descricao': 'XXXX'}]}

In [23]:
with open(path_dados_eixos, 'w') as f:
    json.dump(new_dados_eixos, f, indent=4, ensure_ascii=False)

Agora podemos criar o arquivo de metas e temas com segurança (pois os temas dos eixos foram atualizados com base na planilha)

In [24]:
df.head()

   meta_numero                 tema         eixo
0            1  Natureza e ambiente  Universo SP
1            2  Natureza e ambiente  Universo SP
2            3  Natureza e ambiente  Universo SP
3            4  Natureza e ambiente  Universo SP
4            5  Natureza e ambiente  Universo SP

In [25]:
df_metas = df[['meta_numero', 'tema']].drop_duplicates().reset_index(drop=True)

In [26]:
df_metas.shape

(132, 2)

In [27]:
df_metas['meta_numero'].duplicated().any()

np.False_

In [28]:
metas_temas = {}
for i, row in df_metas.iterrows():
    meta = row['meta_numero']
    if meta in metas_temas:
        raise ValueError(f'Meta {meta} duplicada')

    metas_temas[meta] = row['tema'].strip()

In [29]:
metas_temas

{1: 'Natureza e ambiente',
 2: 'Natureza e ambiente',
 3: 'Natureza e ambiente',
 4: 'Natureza e ambiente',
 5: 'Natureza e ambiente',
 6: 'Natureza e ambiente',
 7: 'Natureza e ambiente',
 8: 'Habitação de qualidade',
 9: 'Habitação de qualidade',
 10: 'Habitação de qualidade',
 11: 'Habitação de qualidade',
 12: 'Infraestrutura e integração',
 13: 'Infraestrutura e integração',
 14: 'Mobilidade',
 15: 'Mobilidade',
 16: 'Mobilidade',
 17: 'Mobilidade',
 18: 'Mobilidade',
 19: 'Mobilidade',
 20: 'Mobilidade',
 21: 'Mobilidade',
 22: 'Mobilidade',
 23: 'Mobilidade',
 24: 'Mobilidade',
 25: 'Mobilidade',
 26: 'Mobilidade',
 27: 'Mobilidade',
 28: 'Mobilidade',
 29: 'Mobilidade',
 30: 'Mobilidade',
 31: 'Infraestrutura e integração',
 32: 'Infraestrutura e integração',
 33: 'Infraestrutura e integração',
 34: 'Infraestrutura e integração',
 35: 'Infraestrutura e integração',
 36: 'Infraestrutura e integração',
 37: 'Infraestrutura e integração',
 38: 'Requalificação urbana',
 39: 'Requalificação urbana',
 40: 'Infraestrutura e integração',
 41: 'Infraestrutura e integração',
 42: 'Infraestrutura e integração',
 43: 'Infraestrutura e integração',
 44: 'Infraestrutura e integração',
 45: 'Mobilidade',
 46: 'Mobilidade',
 47: 'Mobilidade',
 48: 'Infraestrutura e integração',
 49: 'Infraestrutura e integração',
 50: 'Infraestrutura e integração',
 51: 'Requalificação urbana',
 52: 'Requalificação urbana',
 53: 'Requalificação urbana',
 54: 'Mobilidade',
 55: 'Segurança',
 56: 'Segurança',
 57: 'Segurança',
 58: 'Segurança',
 59: 'Segurança',
 60: 'Segurança',
 61: 'Segurança',
 62: 'Segurança',
 63: 'Saúde e bem-estar',
 64: 'Saúde e bem-estar',
 65: 'Saúde e bem-estar',
 66: 'Saúde e bem-estar',
 67: 'Saúde e bem-estar',
 68: 'Saúde e bem-estar',
 69: 'Saúde e bem-estar',
 70: 'Saúde e bem-estar',
 71: 'Saúde e bem-estar',
 72: 'Saúde e bem-estar',
 73: 'Saúde e bem-estar',
 74: 'Saúde e bem-estar',
 75: 'Saúde e bem-estar',
 76: 'Saúde e bem-estar',
 77: 'Educação',
 78: 'Educação',
 79: 'Educação',
 80: 'Educação',
 81: 'Educação',
 82: 'Educação',
 83: 'Educação',
 84: 'Educação',
 85: 'Proteção social e cidadania plena',
 86: 'Proteção social e cidadania plena',
 87: 'Proteção social e cidadania plena',
 88: 'Proteção social e cidadania plena',
 89: 'Proteção social e cidadania plena',
 90: 'Cultura, Esporte e Lazer',
 91: 'Cultura, Esporte e Lazer',
 92: 'Cultura, Esporte e Lazer',
 93: 'Cultura, Esporte e Lazer',
 94: 'Cultura, Esporte e Lazer',
 95: 'Cultura, Esporte e Lazer',
 96: 'Ambiente de negócios',
 97: 'Ambiente de negócios',
 98: 'Ambiente de negócios',
 99: 'Economia criativa',
 100: 'Economia criativa',
 101: 'Economia criativa',
 102: 'Qualificação profissional, emprego e renda',
 103: 'Qualificação profissional, emprego e renda',
 104: 'Qualificação profissional, emprego e renda',
 105: 'Qualificação profissional, emprego e renda',
 106: 'Qualificação profissional, emprego e renda',
 107: 'Ambiente de negócios',
 108: 'Ambiente de negócios',
 109: 'Ambiente de negócios',
 110: 'Economia criativa',
 111: 'Economia criativa',
 112: 'Economia criativa',
 113: 'Modernização e inovação',
 114: 'Modernização e inovação',
 115: 'Modernização e inovação',
 116: 'Transparência e participação cidadã',
 117: 'Modernização e inovação',
 118: 'Governo ágil e acessível a todos',
 119: 'Modernização e inovação',
 120: 'Modernização e inovação',
 121: 'Modernização e inovação',
 122: 'Transparência e participação cidadã',
 123: 'Transparência e participação cidadã',
 124: 'Transparência e participação cidadã',
 125: 'Modernização e inovação',
 126: 'Modernização e inovação',
 127: 'Governo ágil e acessível a todos',
 128: 'Modernização e inovação',
 129: 'Governo ágil e acessível a todos',
 130: 'Governo ágil e acessível a todos',
 131: 'Governo ágil e acessível a todos',
 132: 'Governo ágil e acessível a todos'}

In [30]:
with open('../data/metas_tema.json', 'w') as f:
    json.dump(metas_temas, f, indent=4, ensure_ascii=False)