In [11]:
! pip install pandas
! pip install openpyxl

Requirement already satisfied: pandas in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\d835916\projetos\site-pdm-vfinal-25-28\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [12]:
import pandas as pd
import json

In [13]:
xl_path = '../data/xl/dados_metas_atualizados_v2.xlsx'

In [14]:
df = pd.read_excel(xl_path, engine='openpyxl', sheet_name='Temas, Planos e ODS')

In [15]:
df.head()

,Número da Meta,Destaque do Título,Descrição da Meta,Projeção,Indicador,Secretaria,Eixo,Temas,Subprefeituras,ODS,Nº da Meta ODS,Planos Municipais
0,1,Entregar 8 novos parques,"Entregar 8 novos parques, para ampliar a ofert...","Com essa medida, a cidade chegará a 125 parque...",Número de parques entregues.,SVMA,Universo SP,Natureza e ambiente,Campo Limpo; Casa Verde/Cachoeirinha; Cidade A...,6; 11; 13; 15,11.7; 15.1; 13.1,Plano Diretor Estratégico; Plano Municipal de ...
1,2,Requalificar ou ampliar 25 parques,"Requalificar ou ampliar 25 parques, com a melh...",Serão priorizadas as unidades com indicadores ...,Número de parques revitalizados.,SVMA,Universo SP,Natureza e ambiente,Butantã; Capão Redondo; Ermelino Matarazzo; It...,11; 12; 13; 15,11.7; 15.1; 13.1,Plano Diretor Estratégico; Plano Municipal de ...
2,3,Realizar o projeto São Paulo +Verde,"Realizar o projeto São Paulo +Verde, que vai p...",A iniciativa envolve o plantio de árvores em p...,Número de árvores plantadas.,SVMA; SMSUB,Universo SP,Natureza e ambiente,NaN,2; 6; 11; 12; 13; 15,2.5; 11.7; 13.1; 15.1; 15.2,Plano Municipal de Arborização Urbana
3,4,"Alcançar 11,4% de tratamento de materiais reci...","Alcançar 11,4% de tratamento de materiais reci...",O aumento da capacidade de separação de resídu...,Percentual de resíduos recicláveis não destina...,SP REGULA; SMSUB; SMDET,Universo SP,Natureza e ambiente,NaN,6; 7; 8; 12,12.5; 16.6,Plano de Gestão Integrada de Resíduos Sólidos
4,5,Levar atividades de conscientização e educação...,Levar atividades de conscientização e educação...,Além de cursos e atividades formativas da Univ...,Número de atendimentos em ações de educação am...,SVMA,Universo SP,Natureza e ambiente,NaN,4; 12,3.6; 9.1; 16.6,Plano Municipal de Educação Ambiental

In [16]:
renomear = {
    'Número da Meta' : 'numero_meta',
    'ODS' : 'ods'
}

In [17]:
df.rename(columns=renomear, inplace=True)

In [18]:
df = df[renomear.values()].copy()

In [19]:
df.head()

   numero_meta                   ods
0            1         6; 11; 13; 15
1            2        11; 12; 13; 15
2            3  2; 6; 11; 12; 13; 15
3            4           6; 7; 8; 12
4            5                 4; 12

In [20]:
df['ods'].isnull().any()

np.False_

In [21]:
df['numero_meta'].isnull().any()

np.False_

In [22]:
df['numero_meta'].duplicated().any()

np.False_

In [23]:
parsed_data = {}

for i, row in df.iterrows():

    numero_meta = int(row['numero_meta'])

    ods = str(row['ods']).split(';')

    ods = [int(x.strip()) for x in ods]

    parsed_data[numero_meta] = ods

In [24]:
parsed_data

{1: [6, 11, 13, 15],
 2: [11, 12, 13, 15],
 3: [2, 6, 11, 12, 13, 15],
 4: [6, 7, 8, 12],
 5: [4, 12],
 6: [7, 11, 13],
 7: [7, 11, 13],
 8: [11],
 9: [11],
 10: [6, 11],
 11: [11],
 12: [1, 3, 6, 11, 13],
 13: [11],
 14: [11],
 15: [9, 11],
 16: [9, 11],
 17: [9, 11],
 18: [9, 11],
 19: [9, 11],
 20: [9, 11],
 21: [9, 11],
 22: [9, 11],
 23: [11],
 24: [11],
 25: [11],
 26: [11],
 27: [11],
 28: [11],
 29: [11],
 30: [11],
 31: [9],
 32: [9],
 33: [9],
 34: [9],
 35: [9],
 36: [9],
 37: [6, 9],
 38: [9],
 39: [9],
 40: [9],
 41: [9],
 42: [9],
 43: [9],
 44: [9],
 45: [9, 11],
 46: [3],
 47: [3, 9],
 48: [3],
 49: [9],
 50: [9],
 51: [11],
 52: [11],
 53: [9, 11],
 54: [7, 9, 11, 13],
 55: [16],
 56: [16],
 57: [15, 16],
 58: [16],
 59: [16],
 60: [16],
 61: [16],
 62: [3, 5, 10, 16],
 63: [3],
 64: [3],
 65: [3],
 66: [3],
 67: [3],
 68: [3],
 69: [3],
 70: [3],
 71: [3, 10],
 72: [3, 4, 10],
 73: [3, 10],
 74: [5, 10],
 75: [3],
 76: [3],
 77: [4],
 78: [1, 4, 5, 11],
 79: [4],
 80: [4],
 81: [4],
 82: [4],
 83: [4],
 84: [4],
 85: [1, 2],
 86: [1, 6],
 87: [1, 10, 16],
 88: [1],
 89: [9],
 90: [3],
 91: [3],
 92: [3, 4],
 93: [11],
 94: [4, 11],
 95: [10],
 96: [8, 9, 16],
 97: [8, 9],
 98: [8, 9],
 99: [8],
 100: [11],
 101: [8, 10],
 102: [4, 8, 10],
 103: [4],
 104: [4, 8, 10],
 105: [4, 8, 10],
 106: [8, 10],
 107: [8, 9, 10],
 108: [8, 10],
 109: [2, 8, 10, 12, 15],
 110: [8],
 111: [9],
 112: [8],
 113: [17],
 114: [13],
 115: [17],
 116: [16],
 117: [9, 11, 12, 13],
 118: [16],
 119: [8, 9],
 120: [8, 9],
 121: [13],
 122: [16],
 123: [16],
 124: [16],
 125: [16, 17],
 126: [16, 17],
 127: [16],
 128: [16],
 129: [16],
 130: [16],
 131: [16],
 132: [16]}

In [25]:
with open('../data/metas_ods.json', 'w') as f:
    json.dump(parsed_data, f, indent=4, ensure_ascii=False)