In [1]:
!pip install pandas

Requirement already satisfied: pandas in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/h-pgy/projects/site-pdm-vfinal-25-28/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import os
import json
import re
import copy

In [3]:
path_dados_modulo = '../../data'
path_csv = os.path.join(path_dados_modulo, 'csv/dados_devolutivas.csv')

assert os.path.exists(path_csv)

In [4]:
df = pd.read_csv(path_csv)

In [5]:
df.head()

,id_dev,id_cpma,id_participe_mais,canal_pad,tipo_origem,municipe_pad,titulo,resumo,conteudo_ajustado,tema_pad,orgao,devolutiva,apoios,total_comentarios,subprefeitura_pad
0,6123,420,3808.0,Participe Mais,proposta,Ricardo Souza,Segunda Entrada para o Jardim Keralux.,"Agilizar um segundo acesso ao jardim Keralux, ...",Minha proposta visa a criação de um segundo ac...,Obra viária,SMUL,O PIU Arco Leste tem propostas de melhoramento...,17.0,0.0,ERMELINO MATARAZZO
1,6650,6424,3809.0,Participe Mais,proposta,Diana Tsonis,Incorporar políticas federais ao plano de metas,Incorporar ao Plano de metas o Política Nacion...,Existem diversas políticas e planos federais q...,Cultura,SMC,A Secretaria Municipal de Cultura e Economia C...,34.0,0.0,NaN
2,8595,6426,3809.0,Participe Mais,proposta,Diana Tsonis,Incorporar políticas federais ao plano de metas,Incorporar ao Plano de metas o Política Nacion...,Existem diversas políticas e planos federais q...,Desenvolvimento econômico,SMDET,A Prefeitura de São Paulo agradece a contribui...,34.0,0.0,NaN
3,80,6425,3809.0,Participe Mais,proposta,Diana Tsonis,Incorporar políticas federais ao plano de metas,Incorporar ao Plano de metas o Política Nacion...,Existem diversas políticas e planos federais q...,Pessoa em situação de rua,SMDHC,"No que tange à SMDHC, avaliaremos a proposta n...",34.0,0.0,NaN
4,8142,146,3810.0,Participe Mais,proposta,Samuel Caetano Da Silva,Criação do Parque Linear Caxingui,A criação do Parque Linear Caxingui no Morumbi...,Contexto e Justificativa O distrito do Morumbi...,Parques,SVMA,"Não é viável a inserção neste momento, pois a ...",67.0,0.0,NaN

In [6]:
df.columns

Index(['id_dev', 'id_cpma', 'id_participe_mais', 'canal_pad', 'tipo_origem',
       'municipe_pad', 'titulo', 'resumo', 'conteudo_ajustado', 'tema_pad',
       'orgao', 'devolutiva', 'apoios', 'total_comentarios',
       'subprefeitura_pad'],
      dtype='object')

In [7]:
df['tipo_origem'].unique()

array(['proposta', 'revisao', 'fala'], dtype=object)

In [8]:
df['conteudo_ajustado'] = df['conteudo_ajustado'].str.strip()

In [9]:
df['id_contribuicao'] = np.nan

df['is_fala'] = df['tipo_origem']=='fala'

ids_falas = dict()
id_atual=0
remover = ['\n', '\t', '\r']
for i, row in df.iterrows():
    if row['is_fala']:
        fala = row['conteudo_ajustado'].strip()
        for r in remover:
            fala = fala.replace(r, '')
        #colocando a fala ajustada no df
        df.loc[i, 'conteudo_ajustado'] = fala
        if fala not in ids_falas:
            ids_falas[fala]=id_atual
            id_atual += 1
        df.loc[i, 'id_contribuicao'] = ids_falas[fala]
    else:
        df.loc[i, 'id_contribuicao'] = int(row['id_participe_mais'])

assert not df['id_contribuicao'].isnull().any()

df['id_contribuicao'] = df['tipo_origem'].str.slice(0, 3)+'_'+df['id_contribuicao'].astype(int).astype(str).str.zfill(5)

In [10]:
ids_falas[fala]

482

In [11]:
df[df['is_fala']].head()[['conteudo_ajustado', 'id_contribuicao']]

                                      conteudo_ajustado id_contribuicao
1513  A gente convida a senhora Maria Lodi. Senhora ...       fal_00000
1514  A gente convida agora a participar a senhora A...       fal_00001
1515  A gente passa agora para a senhora Telmelita. ...       fal_00002
1516  A gente passa agora para a senhora Telmelita. ...       fal_00002
1517  A gente passa agora para a senhora Telmelita. ...       fal_00002

In [12]:
df.columns

Index(['id_dev', 'id_cpma', 'id_participe_mais', 'canal_pad', 'tipo_origem',
       'municipe_pad', 'titulo', 'resumo', 'conteudo_ajustado', 'tema_pad',
       'orgao', 'devolutiva', 'apoios', 'total_comentarios',
       'subprefeitura_pad', 'id_contribuicao', 'is_fala'],
      dtype='object')

In [13]:
df = df.replace('NA', None)

In [14]:
for col in df.columns:
    if df[col].dtype not in ('object', int):
        df[col] = df[col].fillna(0)
        df[col] = df[col].astype(int)

    if df[col].dtype == 'object':
        df[col] = df[col].replace(np.nan, None)
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace('None', None)

In [15]:
df.dtypes

id_dev                int64
id_cpma               int64
id_participe_mais     int64
canal_pad            object
tipo_origem          object
municipe_pad         object
titulo               object
resumo               object
conteudo_ajustado    object
tema_pad             object
orgao                object
devolutiva           object
apoios                int64
total_comentarios     int64
subprefeitura_pad    object
id_contribuicao      object
is_fala               int64
dtype: object

In [16]:
df['orgao'] = df['orgao'].replace('SPREGULA', 'SPRegula')
df['orgao'] = df['orgao'].replace('SPTURIS', 'SPTuris')
df['orgao'] = df['orgao'].replace('FUND. PAULISTANA', 'FPD')
df['orgao'] = df['orgao'].replace('PREF/CGA', 'SERI')
df['orgao'] = df['orgao'].replace('CASA CIVIL', 'CC')

df['orgao'] = df['orgao'].replace('None', None)

In [17]:
diagnostico = {

}

dados_parsed = []


def add_to_diagnostico(contrib, msg):
    if contrib not in diagnostico:
        diagnostico[contrib] = []
    diagnostico[contrib].append(msg)

def checar_qtds(df_contrib, mapper_colunas_atributos):

    for coluna, nome in mapper_colunas_atributos.items():
        qtd = df_contrib[coluna].nunique()
        if qtd > 1:
            unicos = df_contrib[coluna].unique()
            msg_especifica = f'Mais de um {nome}: {qtd}. {unicos}'
            add_to_diagnostico(contrib, msg_especifica)

def checar_not_null(df_contrib, coluna):
    if df_contrib[coluna].isnull().any():
        msg_especifica = f'Coluna {coluna} tem valor nulo'
        add_to_diagnostico(contrib, msg_especifica)
        return False
    return True


def extract_first_value(df, coluna, convert):

    return convert(df[coluna].iloc[0])

colunas_atributos_str = {
    'id_contribuicao' : 'id_contribuicao',
    'canal_pad' : 'canal',
    'tipo_origem' : 'tipo_origem',
    'municipe_pad' : 'municipe',
    'titulo' : 'titulo',
    'resumo' : 'resumo',
    'conteudo_ajustado' : 'conteudo',
}


colunas_atributos_int = {
    'id_participe_mais' : 'id_participe_mais',
    'apoios' : 'qtd_apoios',
    'total_comentarios' : 'qtd_comentarios',
}

colunas_atributos_many = {
    'subprefeitura_pad' : 'subprefeitura'
}


colunas_devolutiva = {
        'tema_pad' : 'tema',
        'orgao' : 'orgao',
        'devolutiva' : 'devolutiva',
} 


for contrib in df['id_contribuicao'].unique():
    df_contrib = df[df['id_contribuicao']==contrib]
    checar_qtds(df_contrib, colunas_atributos_str)
    checar_qtds(df_contrib, colunas_atributos_int)

    dados_parsed_contrib = {
        nome: extract_first_value(df_contrib, coluna, str)
        for coluna, nome in colunas_atributos_str.items()
    }

    for coluna, nome in colunas_atributos_int.items():
        dados_parsed_contrib[nome] = extract_first_value(df_contrib, coluna, int)

    for coluna, nome in colunas_atributos_many.items():

        dados_parsed_contrib[nome] = list(df_contrib[coluna].values)

    subs_copy = copy.deepcopy(dados_parsed_contrib['subprefeitura'])
    for sub in subs_copy:

        if sub is None or sub.strip()=='':
            dados_parsed_contrib['subprefeitura'].remove(sub)
            continue

        if (',' in sub) or (' e ' in sub) or (';' in sub):
            new_subs = re.split(',| e |;', sub)
            dados_parsed_contrib['subprefeitura'].remove(sub)
            for new_sub in new_subs:
                new_sub = new_sub.strip()
                if new_sub not in dados_parsed_contrib['subprefeitura']:
                    dados_parsed_contrib['subprefeitura'].append(new_sub)
                

        
    dados_parsed_contrib['devolutivas'] = []
    for devolutiva in df_contrib['devolutiva'].unique():
        df_devolutiva = df_contrib[df_contrib['devolutiva'] == devolutiva]

        checar_qtds(df_devolutiva, colunas_devolutiva)
        orgao_null = not checar_not_null(df_devolutiva, 'orgao')
        if orgao_null:
            continue
        dados_parsed_devolutiva = {
            nome: df_devolutiva[coluna].iloc[0]
            for coluna, nome in colunas_devolutiva.items()
        }

        dados_parsed_contrib['devolutivas'].append(dados_parsed_devolutiva)

    dados_parsed.append(dados_parsed_contrib)

In [18]:
df.columns

Index(['id_dev', 'id_cpma', 'id_participe_mais', 'canal_pad', 'tipo_origem',
       'municipe_pad', 'titulo', 'resumo', 'conteudo_ajustado', 'tema_pad',
       'orgao', 'devolutiva', 'apoios', 'total_comentarios',
       'subprefeitura_pad', 'id_contribuicao', 'is_fala'],
      dtype='object')

In [19]:
diagnostico

{}

In [20]:
dados_parsed

[{'id_contribuicao': 'pro_03808',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Ricardo Souza',
  'titulo': 'Segunda Entrada para o Jardim Keralux.',
  'resumo': 'Agilizar um segundo acesso ao jardim Keralux, por estrada construída na parte interna da estação de trem Comendador Ermelino.',
  'conteudo': 'Minha proposta visa a criação de um segundo acesso para o Jardim Keralux, que não seja tão dispendioso financeiramente falando e seja uma ação rapida e com entrega agil. Pois a Rua Dom Jaime Echevarria, é uma opção, pois ela ja esta toda asfaltada e com iluminação publica e ela leva direto para a estação Comendado Ermelino Matarazzo, porem se em comum acordo com o Estado de São Paulo, derrubar o muro que passa pela mesma rua, porem agora dentro da massa falida da PanQuimica, Viscofam e ai sim se derruba o segundo muro e ja faz a interligação com a a rua principal do jardim Keralux que é a Arlindo Betio. Uma proposta rapida, que não tera necessidade de gastos astronomicos, que o possivel gasto com um viaduto que sera muito caro, e rapido, pois muitas pessoas ja utilizam essa rua para irem para suas casas naquela região.',
  'id_participe_mais': 3808,
  'qtd_apoios': 17,
  'qtd_comentarios': 0,
  'subprefeitura': ['ERMELINO MATARAZZO'],
  'devolutivas': [{'tema': 'Obra viária',
    'orgao': 'SMUL',
    'devolutiva': 'O PIU Arco Leste tem propostas de melhoramentos viários para conexão dessa localidade com as Estações da CPTM USP Leste e Comendador Ermelino, conexão com a Rodovia Ayrton Senna, assim como proposta de transposiçao da ferrovia, por meio de viaduto, na altura da estação comendador Ermelino.'}]},
 {'id_contribuicao': 'pro_03809',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Diana Tsonis',
  'titulo': 'Incorporar políticas federais ao plano de metas',
  'resumo': 'Incorporar ao Plano de metas o Política Nacional de cultura ; a Politica Nacional do Cuidado; a Política Nacional para a População em Situação de Rua; a Política Nacional de Economia Solidária e a Política Nacional de Agricultura Urbana e Periurbana; a Política Nacional de Resíduos Sólidos.',
  'conteudo': 'Existem diversas políticas e planos federais que são de adesão voluntária dos municípios. Estas políticas apresentam soluções viáveis e importantes para o desenvolvimento da cidade de SP. É importante que estes conceitos estejam no Plano de Metas e o compromisso de cumprir estes planos que são fundamentais para o cidadãos. Plano Nacional de cultura: o Sistema Nacional serve para que as políticas culturais se organizem e sejam criadas a partir de potências e demandas regionais, territoriais e setoriais. Prevê o Conselho, Plano e fundo para a cultura. Política Nacional do Cuidado: visa a promoção de trabalho decente para os trabalhadores do cuidado, especialmente nas famílias. A política busca, ainda, redistribuir o trabalho de cuidado, que, tradicionalmente, recai sobre as mulheres, aliviando a sobrecarga sobre esse grupo. Política Nacional para a População em Situação de Rua: Atualmente existem 93.355 pessoas em situação de rua em São Paulo, segundo O Metrópolis, o programa de metas apresentado prevê o atendimento de apenas 3000 pessoas. . Política Nacional de Economia Solidária: a política envolve fortalecer o cooperativismo e o associativismo, promover a justiça social, melhorar a qualidade de vida, gerar renda. Política Nacional de Agricultura Urbana e Periurbana: visa investir na agricultura urbana, vai promover segurança alimentar, reduzir o desperdício e fortalecer a economia local, utilizando espaços urbanos de maneira eficiente e sustentável.',
  'id_participe_mais': 3809,
  'qtd_apoios': 34,
  'qtd_comentarios': 0,
  'subprefeitura': [],
  'devolutivas': [{'tema': 'Cultura',
    'orgao': 'SMC',
    'devolutiva': 'A Secretaria Municipal de Cultura e Economia Criativa reconhece a importância da implementação do Sistema Municipal de Cultura. Informa que já trabalha para a implementação de um novo Plano e a efetivação do Fundo e do Conselho. No entanto, por já existirem um quadro normativo e esforços para a conclusão desses três elementos (Plano, Fundo e Conselho), o Sistema não configura uma entrega, e por isso não configurará na Versão Final do Programa de Metas 2025-2028. Mesmo assim, ressalta-se que a Prefeitura continuará trabalhando na efetiva implementação do Sistema.'},
   {'tema': 'Desenvolvimento econômico',
    'orgao': 'SMDET',
    'devolutiva': 'A Prefeitura de São Paulo agradece a contribuição e esclarece que a metodologia de elaboração de um instrumento de planejamento como o Programa de Metas municipal possui, com umas de suas diretrizes, estar em alinhamento estratégico com normativos, regulamentos e políticas nacionais de maneira a gerar sinergia para elevar a eficácia e efetividade das políticas públicas e entregar melhores resultados ao cidadão. Um exemplo ilustrativo é o Programa Sampa +Rural, que contempla todas as características mencionadas no trecho sobre Política Nacional de Agricultura Urbana e Periurbana e, por meio da Meta 106, apresenta um conjunto de ações estratégicas que colocam em prática as diretrizes estabelecidas por essa política nacional. Importante também informar que a Coordenadoria de Agricultura da Secretaria Municipal de Desenvolvimento Econômico e Trabalho, que lidera o programa Sampa+Rural, apoiaram tecnicamente a elaboração do "Guia para agendas municipais de agricultura urbana e periurbana", instrumento do governo federal realizado em conjunto com o PNUMA/ONU que traz orientações à implantação  de políticas públicas específicas para a agricultura urbana e periurbana nos municípios. Cabe citar também o Plano de Agroecologia e Desenvolvimento Rural Sustentável - Plano Rural, elaborado de forma participativa com a sociedade e instituído pelo Decreto Municipal 62.610 de 2023, que contempla políticas para a Cultura, no Eixo Cultura, do Núcleo Temático Sociocultural e Ambiental, com as diretrizes de (i) preservar a memória, identidade e herança cultural dos agricultores, agricultoras, povos indígenas e de matriz africana para valorização da sociobiodiversidade e (ii) fortalecer e valorizar a cultura da juventude inserida nas atividades da agricultura. Ainda, as políticas para Economia Solidária estão contempladas no Plano Rural no Eixo Comercialização, do Núcleo Temático Econômico Produtivo, com as diretriz de estruturar as cadeias de produção, comercialização e consumo, promovendo a rentabilidade sustentável do setor agropecuário, priorizando a economia solidária, os circuitos curtos de produção e consumo e o acesso das populações das periferias e próximas às áreas de produção. Também, as políticas para os resíduos sólidos que sejam assimiláveis pela agricultura agroecológica estão contemplados no Plano Rural nos Eixos de Agricultura Urbana e de Ensino e Educação do Núcleo Temático Econômico e Produtivo e no Eixo Infraestrutura Básica, do Núcleo Temático Infraestrutura básica e serviços públicos. O Plano Rural dá as diretrizes para a implantação do Programa Sampa+Rural, contemplado pela meta 106 deste Programa de Metas.'},
   {'tema': 'Pessoa em situação de rua',
    'orgao': 'SMDHC',
    'devolutiva': 'No que tange à SMDHC, avaliaremos a proposta no que se refere ao tema "população em situação de rua". Atualmente há análises internas no âmbito da Prefeitura para a internalização da Política Nacional para a População em Situação de Rua. Em complemento, já existe a sua versão municipal, cujas diretrizes são seguidas para a elaboração dos programas voltados à população em situação de rua. Para mais informações sobre o Plano Municipal  de Políticas para a População em Situação de Rua, acesse o link a seguir: https://drive.prefeitura.sp.gov.br/cidade/secretarias/upload/direitos_humanos/Plano%20PopRua.pdf.'}]},
 {'id_contribuicao': 'pro_03810',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Samuel Caetano Da Silva',
  'titulo': 'Criação do Parque Linear Caxingui',
  'resumo': 'A criação do Parque Linear Caxingui no Morumbi visa transformar as margens do Córrego Caxingui em área de lazer e preservação ambiental, atendendo a uma demanda antiga da comunidade. Já previsto no Plano Diretor, o parque é urgente por sua importância hídrica e apoio popular. Apoie essa iniciativa!',
  'conteudo': 'Contexto e Justificativa O distrito do Morumbi, apesar de seu crescimento populacional e econômico, historicamente tem sido negligenciado nas discussões e formulações de políticas públicas pela Subprefeitura do Butantã. Enquanto outras regiões recebem investimentos em infraestrutura, lazer e meio ambiente, o Morumbi carece de iniciativas municipais que atendam às demandas de sua comunidade. A criação do Parque Linear Caxingui é uma demanda antiga da população, já prevista no Plano Diretor Estratégico (Lei 16.050/2014) e identificada como prioritária pela própria Subprefeitura do Butantã em 2008. Trata-se de uma oportunidade única de transformar uma área estratégica em um espaço de convivência, preservação ambiental e qualidade de vida para os moradores.',
  'id_participe_mais': 3810,
  'qtd_apoios': 67,
  'qtd_comentarios': 0,
  'subprefeitura': [],
  'devolutivas': [{'tema': 'Parques',
    'orgao': 'SVMA',
    'devolutiva': 'Não é viável a inserção neste momento, pois a implantação de um parque exige estudo e planejamento prévio. Contudo, esse estudo de viabilidade pode ser realizado fora do escopo do PdM.'}]},
 {'id_contribuicao': 'pro_03811',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Antonio Luiz Da Silva',
  'titulo': 'CRIAÇÃO DA UBS JD. CABUÇU',
  'resumo': 'Propomos a criação da UBS JD. Cabuçu no distrito do Jaçanã. A Atual "Pq Edu Chaves" abrange um território muito grande com mais de 20 mil municipes.',
  'conteudo': 'A região do jd. modelo/Jd. Cabucu entre outros bairros do outro lado da Rodovia, são cobertas pela UBS Pq Edu Chaves, a mesma está saturada com o aumento populacional da região. O tempo médio de espera por uma consulta com o médico generalista é de 30 dias. A anos que essa luta vem sendo tratada e por questões politicas não avança. O local onde foi proposto de fazer a unidade já foi vistiriado pela CRSN e pela SMS, fica na praça do "antigo telecentro" Rua Miguel Arrojado Lisboa, 299. o local dispõe de fácil acesso as escolas da região, linhas de onibus e uma área carente que utiliza 90% do SUS.',
  'id_participe_mais': 3811,
  'qtd_apoios': 26,
  'qtd_comentarios': 1,
  'subprefeitura': ['JACANA-TREMEMBE'],
  'devolutivas': [{'tema': 'Saúde',
    'orgao': 'SMS',
    'devolutiva': 'A meta 61 do Programa de Metas 2025-2028 englobará a entrega de novas instalações de 16 novas instalações, ampliando a qualidade da infraestrutura municipal de saúde. A definição das unidades contempladas com novas instalações foram orientadas por critérios como estado da infraestrutura, necessidades de saúde no território e a disponibilidade de recursos orçamentários. Entre tais unidade, estão: UBS Alto do Umuarama, UBS Bororé (Alcina Pimentel), UBS Butantã, UBS Cantinho do Céu, UBS Eng. Trindade, UBS Jardim Fontalis, UBS Ipojuca, UBS Jardim Helena, UBS Jardim Julieta, UBS Jardim Lapenna, UBS Jardim Robru, UBS Jardim Popular, UBS Jardim Vitória, UBS Real Parque, UBS Recanto dos Humildes, UBS Santa Luzia, UBS Cidade Dutra, UBS Jardim Brasília, UBS Jardim Kioto, UBS Jardim Progresso, UBS Nova Conquista, UBS Parque Savoy, UBS Primavera Colorado, UBS Raposo Tavares e UBS Vila Rubi.'}]},
 {'id_contribuicao': 'pro_03814',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Marcos Batalha',
  'titulo': 'Conselho Municipal de  Esportes - Fundo  municipal do Esporte',
  'resumo': 'Fazer  funcionar o  Conselho Municipal de  Esporte e  o Fundo Municipal de  Esporte',
  'conteudo': 'Que a secretaria Municipal de Esportes faça funcionar o Conselho Municipal de Esporte , com a ampla participação da sociedade , das entidades esportivas e com os atletas de diversas modalidades , que a secretaria faça funcionar o fundo municipal de esportes , que hoje em dia vem d eixando de arrecadar e de receber auxilios de parcerias de termo de colaboração e acordo de cooperação de governos estrangeiros e que possibilitaria o financiamento de diversos projetos esportivos .',
  'id_participe_mais': 3814,
  'qtd_apoios': 27,
  'qtd_comentarios': 0,
  'subprefeitura': [],
  'devolutivas': [{'tema': 'Esporte',
    'orgao': 'SEME',
    'devolutiva': 'A proposta apresentada tem a possibilidade de ser executada, considerando-se a atual meta 88 do PDM, que prevê a requalificação de 65 equipamentos esportivos. É importante destacar que a definição de quais equipamentos receberão as obras ainda está em processo de definição'}]},
 {'id_contribuicao': 'pro_03815',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Marcos Batalha',
  'titulo': 'CMDCA e Fundo da  Infância e  adolescência',
  'resumo': 'Fortalecimento  do CMDCA , para  que  este  conselho possa  fazer a capitação de  recursos  para o FIA - Fundo da  infância e  juventude',
  'conteudo': 'Que a Prefeitura atraves da secretaria Municipal dos Direitos Humanos e cidadania , fortaleça o funcionamento correto do CMDCA de São paulo , e que auxilie o mesmo para trabalhar na capitação dos recursos para o FIA - Fundo da infância e juventude que só aqui em São paulo capital o potencial de arrecadação passa dos 800 milhoes de reais podendo beneficiar vários programas para criança e adolescente e que infelizmente nada é feito .',
  'id_participe_mais': 3815,
  'qtd_apoios': 28,
  'qtd_comentarios': 0,
  'subprefeitura': [],
  'devolutivas': [{'tema': 'Criança e adolescente',
    'orgao': 'SMDHC',
    'devolutiva': 'O Fundo para Infância e Adolescência (FIA) é de competência do Governo do Estado de São Paulo. No âmbito municipal há o Fundo Municipal dos Direitos da Criança e do Adolescente (FUMCAD). Segundo a Lei nº 11.247/1992, a finalidade desse fundo é "[...] proporcionar os meios financeiros complementares às ações necessárias ao desenvolvimento das políticas públicas destinadas à criança e ao adolescente, bem como ao exercício das competências do Conselho Municipal dos Direitos da Criança e do Adolescente e dos Conselhos Tutelares" (art. 01º). Dessa forma, a proposta apresentada já é realizada via fundo municipal. Para mais informações sobre o FUMCAD e sobre todos os seus projetos financiados, sugerimos que acesse o site: https://fumcad.prefeitura.sp.gov.br/.'}]},
 {'id_contribuicao': 'pro_03816',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Juliano Tuschtler Araújo Carvalho',
  'titulo': 'Criação de Espaços Gastronômicos em Parques e Praças Municipais',
  'resumo': 'Proposta para implantar áreas gastronômicas em parques municipais, estimulando convívio social, segurança e economia local. Espaços com food trucks e quiosques revitalizam áreas subutilizadas, gerando emprego e atratividade urbana',
  'conteudo': 'Objetivo: Implementar espaços gastronômicos em parques e praças municipais, a fim de revitalizar áreas subutilizadas, estimular a convivência comunitária e reduzir a sensação de insegurança. Justificativa: A criação de um espaço gastronômico (como food trucks, quiosques ou bistrôs) atrairia moradores, aumentaria a circulação de pessoas e melhoraria a segurança naturalmente – além de impulsionar a economia local. Benefícios: ✅ Aumento da segurança – Mais movimento desincentiva a criminalidade. ✅ Revitalização urbana – Atrai moradores e valoriza o espaço público. ✅ Geração de emprego e renda – Oportunidades para pequenos empreendedores. ✅ Incentivo ao turismo local – Praças movimentadas tornam-se atrativos. ✅ Integração comunitária – Espaços de alimentação promovem convívio social.',
  'id_participe_mais': 3816,
  'qtd_apoios': 35,
  'qtd_comentarios': 3,
  'subprefeitura': ['BUTANTA'],
  'devolutivas': [{'tema': 'Parques',
    'orgao': 'SVMA',
    'devolutiva': 'Não é viável a inserção neste momento, pois a implantação de um parque exige estudo e planejamento prévio. Contudo, esse estudo de viabilidade pode ser realizado fora do escopo do PdM.'}]},
 {'id_contribuicao': 'pro_03819',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Samuel Caetano Da Silva',
  'titulo': 'Aterramento de Fios de Energia Elétrica em Vias Coletoras',
  'resumo': 'A presente proposta sugere a inclusão de recursos para o aterramento dos fios de energia elétrica em vias coletoras estratégicas da cidade. A medida visa eliminar os riscos causados pela rede aérea (queda de postes, interrupções no fornecimento) e melhorar a paisagem com arborização.',
  'conteudo': 'Considerando os altos custos envolvidos no aterramento de redes urbanas, propõe-se a priorização de vias coletoras para o início deste processo, uma vez que a presença de fios aéreos (energia e telecomunicações) nestes locais gera: Poluição visual Riscos à segurança pública Interrupções frequentes de serviços Benefícios da medida: ✔ Segurança: Eliminação de riscos com fios expostos e quedas de postes durante tempestades ✔ Qualidade urbana: Melhoria estética e possibilidade de ampliação de calçadas e arborização ✔ Eficiência: Redução de falhas no fornecimento de energia elétrica ✔ Valorização: Aumento do potencial comercial e residencial das áreas atendidas Sugestão de Implementação: 1. Iniciar por vias com: Alto fluxo de pedestres Histórico de problemas com a rede aérea \u200b\u200b\u200b\u200b\u200b\u200b\u200bPotencial de integração com outros projetos urbanos 2. Priorizar eixos como a Av. Prof. Francisco Morato (Butantã) - que complementaria o viário da Av. Eusébio Matoso, Rebouças.\u200b\u200b\u200b\u200b\u200b\u200b\u200b',
  'id_participe_mais': 3819,
  'qtd_apoios': 73,
  'qtd_comentarios': 3,
  'subprefeitura': ['BUTANTA'],
  'devolutivas': [{'tema': 'Iluminação pública',
    'orgao': 'SPRegula',
    'devolutiva': 'A rede de Iluminação Pública do Município de São Paulo utiliza a infraestrutura da concessionária responsável pela distribuição de energia elétrica Enel, como os postes de concreto, para a instalação das unidades de iluminação pública.\n\nConforme previsto na Resolução Normativa da ANEEL, uma faixa específica dos postes da concessionária de distribuição de energia é destinada exclusivamente à instalação de equipamentos de iluminação pública.\n\nNos casos de enterramento das redes aéreas em determinada região, a iniciativa deve partir da Enel, responsável pelas redes primária e secundária de energia elétrica, bem como pelos postes. Durante o processo de enterramento da rede elétrica da Enel e das redes de telecomunicações, é executada, de forma conjunta, a infraestrutura subterrânea necessária para a iluminação pública das vias.\n\nPortanto, a decisão e o início do processo de enterramento dependem, primordialmente, da concessionária responsável pela distribuição de energia elétrica.'}]},
 {'id_contribuicao': 'pro_03820',
  'canal': 'Participe Mais',
  'tipo_origem': 'proposta',
  'municipe': 'Diana Tsonis',
  'titulo': 'Conceder medida protetiva a toda mulher que solicita',
  'resumo': 'Conceder medida protetiva a toda mulher que solicita. Atualmente nas delegacias a medida protetiva pode ser concedida ou negada. Se a mulher está solicitando proteção é porque ela precisa.',
  'conteudo': 'None',
  'id_participe_mais': 3820,
  'qtd_apoios': 38,
  'qtd_comentarios': 1,
  'subprefeitura': [],
  'devolutivas': [{'tema': 'Segurança',
    'orgao': 'SEPLAN',

In [21]:
diagnostico

{}

In [22]:
diagnostico_to_df = []
for contrib, msgs in diagnostico.items():
    for msg in msgs:
        diagnostico_to_df.append({
            'id_contribuicao': contrib,
            'mensagem': msg
        })

df_diagnostico = pd.DataFrame(diagnostico_to_df)
df_diagnostico.head()

Empty DataFrame
Columns: []
Index: []

In [23]:
df_diagnostico.to_csv('diagnostico.csv', index=False, sep=';')

In [24]:
path_json = os.path.join(path_dados_modulo, 'devolutivas.json')

with open(path_json, 'w', encoding='utf-8') as f:
    json.dump(dados_parsed, f, indent=4, ensure_ascii=False)